version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.9
    steps:
      - checkout
      - run: npm install
      - run: npx tsc
      - run: npm run test-cov
      - run: npm run build
